use_frameworks!

platform :ios, '8.0'

target 'TencentCaptchaSDK_Example' do
  pod 'TencentCaptchaSDK', :path => '../'

  target 'TencentCaptchaSDK_Tests' do
    inherit! :search_paths

    
  end
end
